# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-23 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('bingo', '0008_rename_newword_to_word'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='word',
            unique_together=set([('word', 'site')]),
        ),
    ]
