# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-27 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0011_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='bingo_description',
            field=models.TextField(blank=True, default='', help_text='An optional description of the bingo, that will beshown on the main page. HTML is allowed, so make sure to escape <, > and similar characters correctly and close all your HTML tags.'),
        ),
    ]
